# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/ah632/ece350/whack-a-mole/vivado-whack-a-mole/vivado-whack-a-mole.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ah632/ece350/whack-a-mole/vivado-whack-a-mole/vivado-whack-a-mole.cache/wt [current_project]
set_property parent.project_path C:/Users/ah632/ece350/whack-a-mole/vivado-whack-a-mole/vivado-whack-a-mole.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ah632/ece350/whack-a-mole/vivado-whack-a-mole/vivado-whack-a-mole.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {{C:/Users/ah632/ece350/whack-a-mole/processor/Test Files/Memory Files/monitor_score.mem}}
read_verilog -library xil_defaultlib {
  C:/Users/ah632/ece350/whack-a-mole/processor/RAM.v
  C:/Users/ah632/ece350/whack-a-mole/processor/ROM.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/add.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/alu.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/bitwise_and.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/bitwise_or.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/components/booth_multiplier.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/register/register_components/booths_register.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/cla_block.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/register/counter.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/regfile/components/decoder.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/regfile/components/dffe_ref.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/alu/div_alu_wrapper.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/register/register_components/div_register.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/components/divider.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/falling_dffe_ref.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/falling_ff.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/ff.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/left_shift.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/mole/mod_eight_counter.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/alu/mult_alu_wrapper.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/multdiv.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/multdiv_ctrl_dffe.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/utils/mux32.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/pipeline_latch.v
  C:/Users/ah632/ece350/whack-a-mole/processor/processor.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/program_counter_register.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/regfile/regfile.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/regfile/components/register.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/right_shift.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/multdiv/alu/alu_components/right_shift_64.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/status_latch.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/alu-main/operations/sub.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/utils/program_counter.v
  C:/Users/ah632/ece350/whack-a-mole/processor/components/mole/mole_register.v
  C:/Users/ah632/ece350/whack-a-mole/processor/Wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ah632/ece350/whack-a-mole/master.xdc
set_property used_in_implementation false [get_files C:/Users/ah632/ece350/whack-a-mole/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
